spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: passwd
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
custom:
  fileDirPath: ./files