spring:
  application:
    name: api
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true

springdoc:
  packages-to-scan:
    - com.latinhouse.api.lesson.adapter.in.web
    - com.latinhouse.api.profile.adapter.in.web
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true
