server:
  port: 8080

app:
  jwt:
    secret: "change-me-very-long-and-random-secret-at-least-64-bytes"
    access-exp-minutes: 60
    issuer: "your-app"

spring:
  profiles:
    active: local
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.springnext.demo: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extact: TRACE

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan:
    - com.latinhouse.backend.adapter.in.web
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  cache:
    disabled: true